# Generated by Django 3.2.25 on 2026-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(default='We Bake With Passion', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subheading',
            field=models.CharField(default='// The Best Bakery', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(default='Vero elitr justo clita lorem. Ipsum dolor sed stet sit diam rebum ipsum.', max_length=255),
        ),
    ]
