# Generated by Django 6.1.1 on 2026-09-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20260925_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='mission_text',
            field=models.TextField(default='تقديم خدمات متنوعة للراغبين في الوقف.', verbose_name='نص الرسالة'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_title',
            field=models.CharField(default='رسالتنا', max_length=100, verbose_name='عنوان الرسالة'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_beneficiaries',
            field=models.IntegerField(default=10000, verbose_name='المستفيدين'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_projects',
            field=models.IntegerField(default=50, verbose_name='المشاريع الوقفية'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_years',
            field=models.IntegerField(default=10, verbose_name='سنوات الخبرة'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vision_text',
            field=models.TextField(default='الريادة في تطوير واستدامة الأوقاف.', verbose_name='نص الرؤية'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='vision_title',
            field=models.CharField(default='رؤيتنا', max_length=100, verbose_name='عنوان الرؤية'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(default='نؤسس ونطور الأوقاف', max_length=100, verbose_name='العنوان الرئيسي'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subheading',
            field=models.CharField(default='جمعية رافد للأوقاف', max_length=100, verbose_name='العنوان الفرعي'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(default='جمعية تعنى بتأسيس وتطوير واستدامة الكيانات الوقفية.', max_length=255, verbose_name='النص'),
        ),
    ]
